name: Feature Preview

on:
  workflow_dispatch:
    inputs:
      base_tag_name:
        description: 'Base Tag Name'
        required: false
        default: 'latest'

env:
  TARGET_BRANCH: ${{ github.ref_name }}
  REGISTRY: ghcr.io
  IMAGE_OWNER: skila1

jobs:
  branch_build_setup:
    name: Build Setup
    runs-on: ubuntu-latest
    outputs:
      flat_branch_name: ${{ steps.set_env_variables.outputs.FLAT_BRANCH_NAME }}
      aio_base_tag: ${{ steps.set_env_variables.outputs.AIO_BASE_TAG }}
    steps:
      - id: set_env_variables
        name: Set Environment Variables
        run: |
          if [ "${{ github.event.inputs.base_tag_name }}" != "" ]; then
            echo "AIO_BASE_TAG=${{ github.event.inputs.base_tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "AIO_BASE_TAG=latest" >> $GITHUB_OUTPUT
          fi
          FLAT_BRANCH_NAME=$(echo "${{ env.TARGET_BRANCH }}" | sed 's/[^a-zA-Z0-9]/-/g')
          echo "FLAT_BRANCH_NAME=$FLAT_BRANCH_NAME" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4

  full_build_push:
    runs-on: ubuntu-22.04
    needs: [branch_build_setup]
    permissions:
      contents: read
      packages: write
    env:
      AIO_BASE_TAG: ${{ needs.branch_build_setup.outputs.aio_base_tag }}
      FLAT_BRANCH: ${{ needs.branch_build_setup.outputs.flat_branch_name }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./aio/Dockerfile-app
          platforms: linux/amd64
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/plane-aio-feature:${{ env.FLAT_BRANCH }}
          push: true
          build-args: |
            BUILD_TAG=${{ env.AIO_BASE_TAG }}
            BUILD_TYPE=full
